# Copyright 2025 Xiaomi Corporation.

dataset_path: Zray26/robospatial-context
task: robospatial-context
test_split: test
dataset_kwargs:
  token: True

output_type: generate_until
doc_to_visual: !function utils.robospatial_doc_to_visual
doc_to_text: !function utils.robospatial_doc_to_text_point
doc_to_target: "mask"
generation_kwargs:
  max_new_tokens: 32768
  do_sample: false
  temperature: 0.0
# The return value of process_results will be used by metrics
process_results: !function utils.robospatial_process_results_point
metric_list:
  - metric: accuracy   
    aggregation: !function utils.robospatial_aggregate_results
    higher_is_better: true
metadata:
  - version: 0.0