# Copyright 2025 Xiaomi Corporation.

dataset_path: yifanzhang114/mme-real_world-cn-lmms-eval
task: mmerealworld_cn_boxed
test_split: train
dataset_kwargs:
  token: True

output_type: generate_until
doc_to_visual: !function utils.mme_realworld_doc_to_visual
doc_to_text: !function utils.mme_realworld_cn_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 32768
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
filter_list:
  - name: "flexible-extract"
    filter:
      - function: !function utils.BoxedFilter

process_results: !function utils.mme_realworld_process_results

metric_list:
  - metric: mme_realworld_score
    aggregation: !function utils.mme_realworld_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\n将你的最终答案放在\\boxed{}中。"
metadata:
  - version: 0.0
