# Copyright 2025 Xiaomi Corporation.

dataset_path: Zray26/omnidrive_test
task: omnidrive
test_split: test
dataset_kwargs:
  token: True

img_root: "/path/to/your/image_or_video_data"
output_type: generate_until

doc_to_visual: !function utils.doc_to_visual_as_videos
doc_to_text: !function utils.doc_to_text
doc_to_target: !function utils.doc_to_target

generation_kwargs:
  max_new_tokens: 32768
  temperature: 0
  do_sample: False

lmms_eval_specific_kwargs:
  default:
    pre_prompt: "1: <video> 2: <video> 3: <video> 4: <video> 5: <video> 6: <video>. These six videos are the front view, front left view, front right view, back view, back left view and back right view of the ego vehicle. "
    post_prompt: ""
    
filter_list:
  - name: "flexible-extract"
    filter:
      - function: !function utils.AnswerFilter
        group_select: 0
        ignore_case: true
        ignore_punctuation: true
        regex_pattern: "([A-Z])\\."

process_results: !function utils.process_results_omni

metric_list:
  - metric: omni_gen
    aggregation: !function utils.aggregate_omni_result
    higher_is_better: true

